// Scientific Ways

#pragma once

#include "ScWGameCore.h"

#include "NativeGameplayTags.h"

#define MODULE_API SCWGAMECORE_API

namespace FScWCoreTags
{
	MODULE_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Init states
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// Abilities
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Flashlight);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Jump);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Sprint);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Crouch);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_WalkSlow);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Handheld_Swing);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);

	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelBy_Stunned);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelBy_JumpActivate);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelBy_SprintActivate);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelBy_CrouchActivate);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelBy_WalkSlowActivate);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelBy_SwingActivate);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelBy_InteractActivate);

	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Event_Activated);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Event_Commited);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Event_Failed);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Event_Ended);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Event_Cancelled);

	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_OwnerDead);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_GameMode);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_IgnoreDeath);

	// Pawn
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pawn_Type_Player);

	// Input
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Movement);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look_Mouse);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look_Stick);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Pressed);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Released);

	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Block);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Block_Movement);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Block_Look);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Block_Ability);

	// Camera
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Camera_Type_FirstPerson);

	// Collisions
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Collision);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Collision_None);

	// Set by caller
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Duration);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Magnitude);

	// Cheats
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_NoTarget);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_Invulnerable);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);
	
	// Movement states
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Jumping);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crouching);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_WalkingSlow);

	// Capability states
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead_Started);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead_Finished);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Ragdoll);

	// Damage states
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_IgnoreAnyDamage);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_BlockAnyDamage);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_EvadeAnyDamage);

	// Ability-driven states
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_FlashlightOn);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Swinging);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interacting);

	// Movement modes
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_None);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Walking);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_NavWalking);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Falling);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Swimming);
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Flying);

	// Cues
	MODULE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Damage_Impact);
}

#undef MODULE_API
